// AUTO-GENERATED by scripts/generate-active-locale.mjs en — do not edit
// by hand, it's overwritten on the next dev/build run. See that script's
// own doc comment.
export { dictionary } from './en'
export type { Dictionary } from './en'
